name: Push nightly BTS Images

on:
  push:
    branches:
      - develop

jobs:
  build_and_push_bts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build BeaverTripleService images
        run: |
          docker build ../../ --file Dockerfile --target dev --tag ghcr.io/${{ github.repository_owner }}/quickmpc-bts:${{ github.run_id }}
          docker build ../../ --file Dockerfile --target dep-runner --tag ghcr.io/${{ github.repository_owner }}/quickmpc-bts:${{ github.run_id }}-alpine
        working-directory: ./src/BeaverTripleService/

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-bts:${{ github.run_id }}
          docker push ghcr.io/${{ github.repository_owner }}/quickmpc-bts:${{ github.run_id }}-alpine

  build_and_push:
    runs-on: ubuntu-latest
    needs: [build_and_push_bts]

    steps:
      - name: Merge All build_and_push
        run: echo "ok"
