name: Build BTS and Run Build and Test in Container

on:
  pull_request:
    branches: [develop, master]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  small_test_bts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build images BeaverTripleService
        run: make test m=build
        working-directory: ./Test/

      - name: Run test in BeaverTripleService
        run: make test m=run
        working-directory: ./Test

  small_test:
    runs-on: ubuntu-latest
    needs: [small_test_bts]

    steps:
      - name: Merge All small_test
        run: echo "ok"

  # LargeテストのためCCのイメージをpush
  build_and_push_bts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build CC image
        run: |
          docker build ../../ --file Dockerfile --target dev --tag ghcr.io/${{ github.repository_owner }}/bts_dev:${{ github.run_id }}
          docker build ../../ --file Dockerfile --target medium --tag ghcr.io/${{ github.repository_owner }}/bts_medium:${{ github.run_id }}
        working-directory: ./src/BeaverTripleService/

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/bts_dev:${{ github.run_id }}
          docker push ghcr.io/${{ github.repository_owner }}/bts_medium:${{ github.run_id }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [build_and_push_bts]

    steps:
      - name: Merge All build_and_push
        run: echo "ok"
