name: Build BTS and Run Build and Test in Container

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  small_test_bts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build BeaverTripleService binary
        run: make test m=build
        working-directory: ./Test/

      - name: Run test in BeaverTripleService
        run: make test m=run
        working-directory: ./Test

  small_test:
    runs-on: ubuntu-latest
    needs: [small_test_bts]

    steps:
      - name: Merge All small_test
        run: echo "ok"
